services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express_api
    restart: unless-stopped
    ports:
      - "3006:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    networks:
      - nginx_networks
networks:
  nginx_networks:
    external: true
